name: Setup Terraform
description: |
  This action sets up [Terraform CLI](https://www.terraform.io/) in your GitHub Actions workflow by:

  - Downloading a specified version of Terraform CLI and adding it to the 'PATH'
  - Verifying that the downloaded binary is created and signed by HashiCorp before installation

  This enables Terraform CLI commands to execute just like they do on your local environment.

  ## Usage

  ```yaml
    steps:
      - name: Setup Terraform
        uses: tmknom/setup-terraform-action@v0
        with:
          terraform-version: 1.2.3
  ```

inputs:
  terraform-version:
    required: false
    description: The version of Terraform CLI to install.

runs:
  using: composite

  steps:
    - name: Create install dir
      id: install
      run: |
        echo "::group::Create install dir"
        set -x
        repo="$(cut -d / -f 7 <<<"${GITHUB_ACTION_PATH}")"
        owner="$(cut -d / -f 6 <<<"${GITHUB_ACTION_PATH}")"
        install_dir="${RUNNER_TEMP}/__${owner}-${repo}"
        echo "path=${install_dir}" >> "${GITHUB_OUTPUT}"
        mkdir -p "${install_dir}"
        echo "::endgroup::"
      shell: bash

    # Security at HashiCorp
    # https://www.hashicorp.com/trust/security
    - name: Import PGP public key
      working-directory: ${{ steps.install.outputs.path }}
      run: |
        echo "::group::Import PGP public key"
        set -x
        key_file="pgp-key.txt"
        curl -sSLO "https://www.hashicorp.com/.well-known/${key_file}"
        gpg --import "${key_file}"
        echo "::endgroup::"
      shell: bash

    # Verify HashiCorp binary downloads
    # https://developer.hashicorp.com/well-architected-framework/operational-excellence/verify-hashicorp-binary
    - name: Install Terraform
      working-directory: ${{ steps.install.outputs.path }}
      env:
        VERSION: ${{ inputs.terraform-version }}
      run: |
        echo "::group::Install Terraform"
        set -x
        archive_file="terraform_${VERSION}_linux_amd64.zip"
        checksum_file="terraform_${VERSION}_SHA256SUMS"
        signature_file="terraform_${VERSION}_SHA256SUMS.sig"

        # Download archive, checksum, and signature files
        base_url="https://releases.hashicorp.com/terraform/${VERSION}"
        curl -sSLO "${base_url}/${archive_file}"
        curl -sSLO "${base_url}/${checksum_file}"
        curl -sSLO "${base_url}/${signature_file}"

        # Verify signature and checksum files
        gpg --verify "${signature_file}" "${checksum_file}"

        # Verify checksum and archive files
        grep "${archive_file}" "${checksum_file}" | sha256sum --check

        # Install binary and set path variables
        bin_path="${PWD}/bin"
        mkdir -p "${bin_path}"
        unzip "${PWD}/${archive_file}" -d "${bin_path}"
        echo "${bin_path}" >> "${GITHUB_PATH}"
        echo "::endgroup::"
      shell: bash
